name: Subscribe-zhihu

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: send trigger curl
        uses: indiesdev/curl@v1.1
        with:
          method: 'POST'
          url: ${{ secrets.WORKER_URL }}
          timeout: 100000
