// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	AI: Ai;
	// repo token for write and modify
	REPO_TOKEN: string;
	ENV?: 'dev';
}
