// Generated by Wrangler on Sat Aug 17 2024 14:05:47 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	AI: Ai;
	// repo token for write and modify
	REPO_TOKEN: string;
	ENV?: 'dev';
	ZHIHU_COOKIE: string;
	LOGGER: R2Bucket;
	SELF_EMAIL: string;
	TR_SERVE: string;
}
